FROM python:3.6.5
WORKDIR /usr/src/app
COPY ut-requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN rm -f ./requirements.txt
COPY ./src ./src
COPY ./test ./test
COPY ./ut-config /etc/mtc/
ENV PYTHONPATH=$PYTHONPATH:/usr/src/app/src
ENTRYPOINT ["python", "./test/ut_run.py"]